;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-defun
        c-electric-paren
        dabbrev-expand
        kill-region
        mark-paragraph
        mark-sexp
        mark-word
        markdown-cycle
        paredit-backward-kill-word
        paredit-backward-up
        paredit-close-round
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        paredit-open-round
        paredit-raise-sexp
        paredit-reindent-defun
        paredit-semicolon
        paredit-splice-sexp
        paredit-wrap-round
        slime-autodoc-space
        transpose-sexps
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        cider-eval-defun-at-point
        end-of-buffer
        jao-toggle-selective-display
        paredit-forward-up
        prolog-mark-clause
        ))
